### PR TITLE
We made all index.html and style.css neccesary changes

### PR DESCRIPTION
**Pull request by Miguelus373**
We finished the Youtube page clone, organize the CSS file, and fixed every bug.

We are waiting for this project to be reviewed.

### CODE REVIEW

**Review by expjazz — CHANGES_REQUESTED** [review]
## Hello @Miguelus373  and @diazgio !

#### You did a good job, but unfortunately, the repo does not meet all the requirements and I need to mark as invalid :crying_cat_face: :
- The Readme file in the repo is not descriptive (it has almost no content). Please check out this template: https://github.com/microverseinc/readme-template
- You did most of the commits in the master branch. For the next project, please do them in the feature branch and then do the PR to merge in master.
- You can see more here in this link: https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

#### Again, you really did great work, but the reasons above this Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

ps: If you have any questions, please reach out on slack  @expedito

**Comment by diazgio** [comment]
We changed the readme in the feature-branch.

**Review by expjazz — CHANGES_REQUESTED** [review]
## Hey @Miguelus373  and @diazgio

### [Changes Required]

#### The readme file now is great, but we still need to change a few things to get this project approved:

- [ ] The likes, dislike, views, and dates are not aligned, as the user's avatar with the video name. Check also the subscribe button (the word subscribe is not complete)

#### Yours 
:point_down:
image

#### Original 
:point_down:
image

- [ ] The HTML has not been validated. Please do this step before submitting it for a new review.

- [ ] On your CSS, you have a set of properties applied to three different elements identified by Ids (line 97 and 102 of your CSS). In this case, I think that it would be better to use classes.

[Optional]

- The height of the embedded video is too high. It would look better if it was a little shorter.

#### As stated above, the project looks really good.

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

**Comment by Miguelus373** [comment]
We fix the alignment of the views and buttons, the subscribe button, and the video list images.

We also change all sizes to relative sizes.

**Review by kubilaycaglayan — APPROVED** [review]
Hello Team, 😊 

### Welcome to the Microverse! ✋
We are so glad to see you here. 👀 

I see you have done every required change correctly.
Congratulations, **your project is approved.** 👏

**Pull request merged**
